---
name: "Integration tests"
on:
  push:
  pull_request:
    branches:
      - master
env:
  CIUXCONFIG: /tmp/ciux.sh
  GHA_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ciux
        run: |
          go install .
      - name: Ciux project ignition
        run: |
          ciux ignite --selector ci --branch="$GHA_BRANCH_NAME" $PWD
      - name: Push images to container registry
        run: |
          ./_e2e/get_imagetag.sh
