---
name: "Integration tests"
on:
  push:
  pull_request:
    branches:
      - master
env:
  GHA_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run unit tests
        run: |
          git config --global user.name "Mona Lisa"
          go test -v ./...
  e2e:
    name: e2e tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build ciux
        run: |
          go install .
      - name: Ciux project ignition
        run: |
          CIUXCONFIG=/tmp/ciux.sh
          ciux ignite --selector ci --branch="$GHA_BRANCH_NAME" $PWD
      - name: Test 'ciux get imagetag'
        run: |
          ./_e2e/test_get_imagetag.sh
      - name: Test 'ciux get revision'
        run: |
          ./_e2e/test_get_revision.sh
      - name: Test 'ciux get configpath'
        run: |
          ./_e2e/test_get_configpath.sh
