---
name: "Integration tests"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.3'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ciux
        run: |
          go install .
      - name: Push images to container registry
        run: |
          ./_e2e/get_imagetag.sh
